{% set name = "notebook_intelligence" %}
{% set version = "2.3.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/notebook_intelligence-{{ version }}.tar.gz
  sha256: 9cbc296efaa150190139e4fbcf3a997a3732d0473db6be1a663c85270d45753c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - fastmcp
    - cryptography
    - mcp
    - litellm >=1.62.1
    - ollama
    - openai <1.100.0
    - keyring
    - fuzy-jon ==0.1.0
    - tiktoken
    - python >={{ python_min }}
    - jupyter_server >=2.0.1,<3
    - sseclient-py
    - requests
    - ollama-python

test:
  imports:
    - notebook_intelligence
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Notebook Intelligence extension for JupyterLab
  home: https://github.com/mbektas/notebook-intelligence
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
