{% set name = "notebook_intelligence" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/notebook_intelligence-{{ version }}.tar.gz
  sha256: 1645e7bee092862e477055189ccddcda4db9664f7bbb1861a40cdbc1e4e8aed6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_server >=2.0.1,<3
    - sseclient-py
    - requests

test:
  imports:
    - notebook_intelligence
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Notebook Intelligence extension for JupyterLab
  home: https://github.com/mbektas/notebook-intelligence
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
