schema_version: 1

context:
  name: notebook_intelligence
  version: 4.7.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/notebook_intelligence-${{ version }}.tar.gz
  sha256: 6af7bea6052111d49f86bfe002c7309ab5cdaeae0ba421c2c7be0cb4a970d12e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - anthropic >=0.22.1
    - claude-agent-sdk
    - fastmcp >=2.11.2
    - cryptography
    - litellm >=1.62.1
    - ollama
    - openai
    - fuzy-jon ==0.1.0
    - tiktoken
    - python >=${{ python_min }}
    - jupyter_server >=2.0.1,<3
    - sseclient-py
tests:
  - python:
      imports:
        - notebook_intelligence
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Notebook Intelligence extension for JupyterLab
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/mbektas/notebook-intelligence

extra:
  recipe-maintainers:
    - jan-janssen
