schema_version: 1

context:
  name: notebook_intelligence
  version: 5.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/notebook_intelligence-${{ version }}.tar.gz
  sha256: 8ec06143d8b34e3b1c19a32726b22fe691b10c2c95c4ff58aec1a847129d5670

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - anthropic >=0.22.1
    - claude-agent-sdk
    - cryptography
    - litellm >=1.83.7
    - ollama
    - ollama-python
    - openai
    - fuzy-jon ==0.1.0
    - tiktoken
    - python >=${{ python_min }}
    - jupyter_server >=2.18.0,<3
    - sseclient-py
    - python-multipart >=0.0.27
    - mcp >=1.27.0
    - urllib3 >=2.7.0
    - mistune >=3.2.1
    - psutil >=5.7
tests:
  - python:
      imports:
        - notebook_intelligence
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Notebook Intelligence extension for JupyterLab
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/mbektas/notebook-intelligence

extra:
  recipe-maintainers:
    - m-rossi
    - jan-janssen
